### ISSUE TITLE
Game Crashes After Cutscene Plays

### ISSUE THREAD

**Issue by Behnja** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#10]
Pretty self explanatory. Launch up the game, go into the week with the cutscene I added, it plays out and then the game crashes. I've searched for hours what the problem could possibly be, and it all just leads to nothing. 

However something I noticed was that if I move the "LoadingState" line right below the "video.playMP4" line, the game doesn't crash, but what happens instead is the cutscene does not play and I'm put straight into the week, with the audio of the cutscene playing in the background.
![HELP](https://user-images.githubusercontent.com/65302993/129488440-399cace0-d948-4465-bb59-772b7606bc56.png)

I don't know if I did something wrong with the code. I'm pretty sure I haven't, since I followed Brightfyre's tutorial of Polybius' code step by step, and made sure that I did everything right. Of course if it is me, or Brightfyre's tutorial is already outdated and I just have to do things differently, then let me know.

**Comment by polybiusproxy** [comment]
Hello! Can you send this information?

- Operating System
- Architecture of Operating System
- Logs when FNF crashed.

**Comment by Behnja** [comment]
@polybiusproxy sure! My operating system is Windows 10. I don't know what you mean by "architecture of operating system", but from my searches I think it's x64 bits. Don't really know if there's a certain place or file that includes any type of crash logs, but I just guessed you mean the Windows PowerShell mess of code that it put out so here it is:

**C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:306: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/0,0,2//linc/ -I C:/Users/benig/Desktop/fridaynightfunkinTHEFKNDEGENERATES/Kade-Engine-1.5.2/source/vlc/cpp/include/ -I C:/Users/benig/Desktop/fridaynightfunkinTHEFKNDEGENERATES/Kade-Engine-1.5.2/source/vlc/cpp/src/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\benig\Desktop\fridaynightfunkinTHEFKNDEGENERATES\Kade-Engine-1.5.2\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/ApplicationMain.cpp
 - src/lime/utils/AssetCache.cpp  [haxe,release]
 - src/StoryMenuState.cpp
Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp
source/TitleState.hx:64: Loaded 0 assets (DEFAULT)
source/Discord.hx:13: Discord Client starting...
source/Discord.hx:63: Discord Client initialized
source/Discord.hx:20: Discord Client started.
source/TitleState.hx:322: outdated lmao! 1.6.2 != 1.5.1
source/MusicBeatState.hx:33: reg (x: -200 | y: -200 | w: 1792 | h: 1008)
source/MusicBeatState.hx:33: reg (x: -200 | y: -200 | w: 1792 | h: 1008)
source/MainMenuState.hx:228: Story Menu Selected
source/StoryMenuState.hx:123: Line 70
source/StoryMenuState.hx:149: Line 96
source/StoryMenuState.hx:158: Line 124
source/StoryMenuState.hx:184: Line 150
source/StoryMenuState.hx:200: Line 165
source/MusicBeatState.hx:33: reg (x: -200 | y: -200 | w: 1792 | h: 1008)
source/Song.hx:49: come-hard
source/Song.hx:58: loading come/come-hard
source/Paths.hx:95: assets/videos/scene1.mp4
set location: file:///C:\Users\benig\Desktop\fridaynightfunkinTHEFKNDEGENERATES\Kade-Engine-1.5.2\export\release\windows\bin//assets/videos/scene1.mp4
source/MP4Handler.hx:91: video loaded!
source/MP4Handler.hx:106: Big, Big Chungus, Big Chungus!
source/PlayState.hx:253: Mod chart: false - assets/data/come/modchart.lua
source/Conductor.hx:68: new BPM map BUDDY []
source/PlayState.hx:317: INFORMATION ABOUT WHAT U PLAYIN WIT:
FRAMES: 10
ZONE: 166
TS: 1
BotPlay : false**

Let me know if you need anything else or I got something wrong so I can go back and provide better information.

**Comment by polybiusproxy** [comment]
that is now fixed
download latest version and try again
