### ISSUE TITLE
You need to play a song/week with no cutscene before a song/week with a cutscene or it will crash

### ISSUE THREAD

**Issue by BL0KYBL0K** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#11]
the game crashes after cutscenes end unless you play another song or week first please fix this cause on the mod im working on webm do not work for some reason so i need mp4 please fix this soon
im not add video proof cause i think i explained the problem well but if you need a photo of any of the code ill send it

**Comment by deandimarzo** [comment]
Just made a pull request myself that fixes this problem.

**Comment by polybiusproxy** [comment]
that was fixed with @deandimarzo pull request
