### ISSUE TITLE
Module MP4Handler does not define type MP4Handler

### ISSUE THREAD

**Issue by z0ffy** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#14]
I don't know why it's happening I followed the instructions.
![Capture](https://user-images.githubusercontent.com/69302186/129656893-48d2f9f7-e8d9-4781-9117-e42d4399bb0a.PNG)

**Comment by polybiusproxy** [comment]
brightfyre fucked it up
use lstest version
