### ISSUE TITLE
New Cutscene Code Causes Other Weeks To Crash

### ISSUE THREAD

**Issue by Behnja** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#15]
Hey, it's me again. Your favorite cutscene crash reporter. Guess what I'm here for. Anyways so while playing around with my mod, I decided to enter one of the normal weeks, you know, like Week 4 with Mommy Mearest. I selected the week, clicked enter to play it, and then the game crashed, doesn't even put me in the first song it just crashes. I've been trying to figure out what could possibly be causing this issue, cause it certainly wasn't something to do with Week 4 since the same happened to every single week, well, every single week except my own week...which has a cutscene. It seemed stupid but I decided to give it a try and removed the MP4 video code that goes on StoryMenuState.hx and replace it what originally was there:
![42r](https://user-images.githubusercontent.com/65302993/130343614-61d675d8-46be-4af0-bfe2-132d20861cfc.png)

Saved changes, launched game, and oh would you look at that, I can play the weeks now without issue. I'm confident this is a simply fix, just changing the code a bit, hoping this gets fixed soon. As always if you need anything else like the logs, I'll be quick to provide it.

Edit: I think it's important for me to mention I'm using the latest Kade Engine (1.6.2), which has a bug in which weeks like 3 and 2 crash after playing the first song. Don't know if that helps, but just in case I'll leave yall with that bit of information.

**Comment by Yubaru** [comment]
I'm using kade engine 1.6 and the same problem happened to me. The way I got around it was to get a mp4 video of a black screen that plays for 1 second and have it played on every week (That saying if you want a cutscene playing on one week. You have to have some sort of video playing for every other week). This prevents the crashing. So its the way that its coded, but I'm sure this will get fixed soon. In the meantime this is the code I used. (For StoryMenuState) 

if (curWeek == 2 && !isCutscene) // Checks if the current week is Tutorial.
			{
				video.playMP4(Paths.video('maincutscene'), new PlayState()); 
				isCutscene = true;
			}
			else if (curWeek == 1)
			{
				video.playMP4(Paths.video('blackscreen'), new PlayState()); 
				isCutscene = true;
			}
			else if (curWeek == 0)
			{
				video.playMP4(Paths.video('blackscreen'), new PlayState()); 
				isCutscene = true;
			}
			else
			{
				new FlxTimer().start(1, function(tmr:FlxTimer)
				{
					video.onVLCComplete();
					LoadingState.loadAndSwitchState(new PlayState(), true);
				});
			}
		}
	}


I hope this helps.

**Comment by Behnja** [comment]
@Yubaru nice, thanks for the suggestion!

**Comment by polybiusproxy** [comment]
This must occur since it calls onVLCComplete when there is no video playing.
