### ISSUE TITLE
how to make the video play AFTER it fades to load in the week itself?

### ISSUE THREAD

**Issue by ComradeCat1** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#18]
I tried adding a video to my FNF Mod, but the video plays EXACTLY after the week is selected, and I want it to play after the fade out, LOADS the week, then plays the video, so the week immediately starts.
If this isn't possible at the moment, it's fine, I'll try using WEBM video support instead.

**Comment by polybiusproxy** [comment]
WEBM also does that.
You can check in mods like V.S. Nonsense, video loads after week is selected.

**Comment by CryBitDev** [comment]
@ComradeCat1 I fixed that in the new version of the mp4 support, use that and tell me if it works now!

**Comment by ComradeCat1** [comment]
@CryBitDev Ok, I'll try

**Comment by ComradeCat1** [comment]
Yep, it works now (The Story Mode Menu is no longer visible after playing the video before the week starts), so thank you for fixing the issue. I think I can close this now
