### ISSUE TITLE
Crash when switching into PlayState

### ISSUE THREAD

**Issue by Gabriel55ita** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#2]
Hi, 
I have found a bug: when the cutscene is finished and the game switches to playstate it crash.

Hope it will be fixed

**Comment by polybiusproxy** [comment]
Hi there!
Could you provide these info?

- Operating System
- Log of FNF when it crashed

**Comment by Gabriel55ita** [comment]
I actually fixed the issue
