### ISSUE TITLE
Cutscenes that play before a song overlap if you press enter after you have selected them.

### ISSUE THREAD

**Issue by BMB46** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#24]
So, I am trying to make cutscenes by using this code on StoryMenuState.hx:
			var isCutscene:Bool = false;

			var video:MP4Handler = new MP4Handler();

			if (PlayState.SONG.song.toLowerCase() == 'arc') // Checks if the current week is Tutorial.
			{
   				 video.playMP4(Paths.video('cutscene1'), new PlayState()); 
    			 isCutscene = true;
			}
			else
			{
  			  new FlxTimer().start(1, function(tmr:FlxTimer)
   			 {
      		  if (isCutscene)
          	  video.onVLCComplete();

       		 LoadingState.loadAndSwitchState(new PlayState(), true);
   			 });
			}
And when I start the song the cutscene plays correctly, but if I press enter again, it will replay and overlap and it will do that everytime I press enter during the cutscene, Im not sure if I messed something up, or its a oversight that others havent noticed, any how, I would greatly appreciate any help or tips towards fixing this.

**Comment by CryBitDev** [comment]
Shouldn't the code check the week of the song?

**Comment by CryBitDev** [comment]
And also i think you should add a parameter to the if function if the inCutscene is false.

**Comment by BMB46** [comment]
> Shouldn't the code check the week of the song?

First of all thanks for replying, Im trying to make it so it only plays when that song in specific is played, does this not happen if you just use "curWeek"?

> And also i think you should add a parameter to the if function if the inCutscene is false.

You mean that part that says "&& !isCutscene)"?

**Comment by BMB46** [comment]
Even when replacing it for if (curWeek == 1 && !isCutscene) it still plays again when pressing enter and overlaps.

**Comment by polybiusproxy** [comment]
That was fixed by CryBit.
