### ISSUE TITLE
how do i make a cutscene play AFTER multiple weeks?

### ISSUE THREAD

**Issue by mikeyb520** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#25]
yo, so i'm making a mod, and when i try and make it so every week has a cutscene, it skips every other cutscene for the previous weeks, and only plays the one for the last week.

for example i have 2 weeks in my mod 

week 1 & 2 

i have it so every week plays a cutscene before the level begins, and for me, only week 2's cutscene plays, and it skips week 1's cutscene, and if i go to play week 1, it still skips the cutscene.  i can provide source code if needed, i need help please and thank you.

**Comment by foodcake** [comment]
you could make a switch case for curWeek, case 1:, case 2:, then put the code in those

**Comment by mikeyb520** [comment]
> you could make a switch case for curWeek, case 1:, case 2:, then put the code in those

that helped, thank you!
