### ISSUE TITLE
how to make cutscenes play after a specific song?

### ISSUE THREAD

**Issue by mikeyb520** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#29]
hello again! 

so i  wanna make it so a cutscene plays AFTER the last song in my mod, however when i tried the code the github says to do, it doesn't work, and it just ends the song like normal

any help or code i should try putting? thanks!

**Comment by Epic-Riff** [comment]
put the question lable lol

**Comment by guizinhomartinez** [comment]
look in brightfyre's channel

**Comment by polybiusproxy** [comment]
I will not help with the implementation of the MP4 support since everything is explained in BrightFyre's video, as @guizinhomartinez said.
