### ISSUE TITLE
Crashing while compiling

### ISSUE THREAD

**Issue by Sergierix** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#3]
When I compile the game, it says "source/StoryMenuState.hx:350: characters 15-30 : Type not found : VideoHandlerMP4"
I'm using windows

**Comment by polybiusproxy** [comment]
> Same issue of "VideoHandlerMp4" not included

Hi there, "VideoHandlerMP4" class was replaced with "MP4Handler".
A README.md update will come eventually.
