### ISSUE TITLE
Cutscene enters in a infinite loop

### ISSUE THREAD

**Issue by TheWooomy** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#31]
So there should be a cutscene after the last song of a mod ends, and the cutscene works. But, when the cutscene ends, it shows the third song again, and when the song ends, it shows the cutscene, and then the song again, so it creates a loop. idk how to solve this since i just folllowed the instructions in the github page of the mp4 handler but with those instructions the cutscene showed in all the songs so i stayed with a code based on brightfyre's video.
<img width="960" alt="Captura de pantalla 2021-09-13 092013" src="https://user-images.githubusercontent.com/86993953/133082322-db445b18-ab2f-4b5f-9ddf-86f0d327a57d.png">
https://user-images.githubusercontent.com/86993953/133084098-80e7e942-67d5-44e3-9e20-d57b1a4937b0.mp4

**Comment by polybiusproxy** [comment]
@brightfyregit
