### ISSUE TITLE
Error that i don't know how to fix.

### ISSUE THREAD

**Issue by Gamerofyear** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#36]
Hello! I have a problem. Whenever I build my game this error pops up:

PS I:\Funk\FridayNightMemes\Kade-Engine-1.7> lime test windows
I:/HAXE/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
I:/HAXE/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
**source/StoryMenuState.hx:378: characters 15-30 : Type not found : VideoHandlerMP4_**

I watched the tutorial underneath by brightfire:
[https://www.youtube.com/watch?v=sWOT-7_RSQc&ab_channel=BrightFyre](url)
Can somebody please help me?

**Comment by polybiusproxy** [comment]
Use MP4Handler, not VideoMP4Handler.
