### ISSUE TITLE
I wanted to code a cutscene playing after specific song, and i can't compile my game now

### ISSUE THREAD

**Issue by teotm** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#42]
So I was trying to add the code that plays a Cutscene after a specific song. In this was case this was Tutorial. When I compiled my game i got this error in my Windows PowerShell. 
```
source/PlayState.hx:3434: lines 3434-3437 : Void -> Void should be flixel.FlxState
source/PlayState.hx:3434: lines 3434-3437 : For function argument 'callback'
```
Here's what my code looks like in `PlayState.hx`.
```haxe
if (SONG.song.toLowerCase() == 'tutorial')
{
	var video:MP4Handler = new MP4Handler();
	video.playMP4(Paths.video('myVideoName'), function()
	{
		FlxG.switchState(new PlayState());
	});
}
else
{
	LoadingState.loadAndSwitchState(new PlayState());
}
```
Please send me what my code should look like instead, or tell me what I need to do.
Thank you if you want to help me :)

**Comment by polybiusproxy** [comment]
Do not make it a function.
just use "new PlayState()"

**Comment by teotm** [comment]
So, I fixed the code and my game can compile and here's what my code looks like:
```haxe
if (SONG.song.toLowerCase() == 'tutorial')
{
	var video:MP4Handler = new MP4Handler();
	video.playMP4(Paths.video('myVideoName'), new PlayState());
}
else
{
	LoadingState.loadAndSwitchState(new PlayState());
}
```
and after I beat the song there is no cutsene after the song, and the game takes me to the Story Menu (but if it would be for example Bopeebo, it takes me to fresh)
I honestly don't know what's wrong. Maybe I should edit one of the other `.hx` files?

**Comment by polybiusproxy** [comment]
> So, I fixed the code and my game can compile and here's what my code looks like:
> 
> ```hx
> if (SONG.song.toLowerCase() == 'tutorial')
> {
> 	var video:MP4Handler = new MP4Handler();
> 	video.playMP4(Paths.video('myVideoName'), new PlayState());
> }
> else
> {
> 	LoadingState.loadAndSwitchState(new PlayState());
> }
> ```
> 
> and after I beat the song there is no cutsene after the song, and the game takes me to the Story Menu (but if it would be for example Bopeebo, it takes me to fresh) I honestly don't know what's wrong. Maybe I should edit one of the other `.hx` files?

Where is the code located?

**Comment by teotm** [comment]
In PlayState.hx
