### ISSUE TITLE
My mp4 video doesn't play after a specific song

### ISSUE THREAD

**Issue by teotm** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#44]
So, welcome again. I have no compiling errors, but when I want my cutscene to play after a specific song, the game just ignores the code and doesn't play the video and takes me to Story Menu (if I would restrict it to Tutorial) or another song (if it would be for example Bopeebo). Here's what my code looks like in `PlayState.hx`:
```haxe
if (SONG.song.toLowerCase() == 'tutorial')
{
	var video:MP4Handler = new MP4Handler();
	video.playMP4(Paths.video('myVideoName'), new PlayState());
}
else
{
	LoadingState.loadAndSwitchState(new PlayState());
}
```
I think that I should go to the other lines or another source files to make the Cutscenes play.
I would be really happy if someone would help me.

**Comment by teotm** [comment]
> > So, I fixed the code and my game can compile and here's what my code looks like:
> > ```hx
> > if (SONG.song.toLowerCase() == 'tutorial')
> > {
> > 	var video:MP4Handler = new MP4Handler();
> > 	video.playMP4(Paths.video('myVideoName'), new PlayState());
> > }
> > else
> > {
> > 	LoadingState.loadAndSwitchState(new PlayState());
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and after I beat the song there is no cutsene after the song, and the game takes me to the Story Menu (but if it would be for example Bopeebo, it takes me to fresh) I honestly don't know what's wrong. Maybe I should edit one of the other `.hx` files?
> 
> Where is the code located?

In `PlayState.hx`.

**Comment by MrGrape0** [comment]
I tried the code but I got a ValueException :p
