### ISSUE TITLE
how do you fix this path 

### ISSUE THREAD

**Issue by McJonnycat** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#59]
In file included from ./src/vlc/VlcBitmap.cpp:127:
/Users/Downloads/auditor-demo-main/source/vlc/cpp/src/LibVLC.cpp:5:10: fatal error: 'windows.h' file not found
#include <windows.h> 
         ^~~~~~~~~~~
1 error generated.  

all i need to do is to fix this error

**Comment by polybiusproxy** [comment]
Delete that line and try to compile, it will not work.
Then send what does the logs says.

From my guesses, I see that you're trying to compile for macOS, right?

**Comment by DotWith** [comment]
> Delete that line and try to compile, it will not work. Then send what does the logs says.
> 
> From my guesses, I see that you're trying to compile for macOS, right?

I don't think so he has Users/Download folders

**Comment by Jonnycatmeow** [comment]
> Delete that line and try to compile, it will not work. Then send what does the logs says.
> 
> From my guesses, I see that you're trying to compile for macOS, right?

yeah im trying to make it for macos

**Comment by Jonnycatmeow** [comment]
> > Delete that line and try to compile, it will not work. Then send what does the logs says.
> > From my guesses, I see that you're trying to compile for macOS, right?
> 
> I don't think so he has Users/Download folders

i do
