### ISSUE TITLE
Background assets don't load after MP4 video when Downscroll enabled.

### ISSUE THREAD

**Issue by deandimarzo** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#6]
When using an MP4 video to start a Story week (in Playstate.hx), after the video plays, if Downscroll is enabled, song will load with Haxeflixel icons replacing all background assets for a moment, and then close the program.

Using Kade Engine 1.6.1

**Comment by polybiusproxy** [comment]
That might be a Kade Engine issue.
I didn't tested tho.

I will investigate the issue

**Comment by BL0KYBL0K** [comment]
kade engine 1.6.1 is very glitchy and broken so i suggest using something like 1.5.2 or 1.5.4 instead

**Comment by deandimarzo** [comment]
I actually managed to fix this (and all other random loading errors I was having) by changing any instances of  `FlxG.switchState(finishCallback);` to `LoadingState.loadAndSwitchState(finishCallback);` in MP4Handler.hx.

**Comment by polybiusproxy** [comment]
> I actually managed to fix this (and all other random loading errors I was having) by changing any instances of `FlxG.switchState(finishCallback);` to `LoadingState.loadAndSwitchState(finishCallback);` in MP4Handler.hx.

Cool! Please make a pull request and i'll merge it!
