### ISSUE TITLE
I got a value exception when the video will play,can someone help me please?

### ISSUE THREAD

**Issue by MrGrape0** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#60]
I tried to code a video to play before a song and I got a Value Exception,I'm new to code so I don't know what to do,can someone help me,please???
![image](https://user-images.githubusercontent.com/79094766/142875283-aafa4706-ec51-43a1-858a-ae532889ceb2.png)
![image](https://user-images.githubusercontent.com/79094766/142875303-a676aa49-0ca5-4d6b-b849-f342e6c482a8.png)

**Comment by polybiusproxy** [comment]
Follow the README instructions properly.
