### ISSUE TITLE
[BUG] Error while compiling

### ISSUE THREAD

**Issue by susyboy23** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#68]
**source/states/VideoState.hx:25: characters 32-48 : mp4.MP4Handler does not have a constructor**
it hive me this error, im on windows 10, heres script:
![image](https://user-images.githubusercontent.com/89088882/145635700-0574a514-0f34-4fb8-a73f-6c3e105a2c4e.png)
some one knows how to solve this?

**Comment by DotWith** [comment]
use the create function you moron

**Comment by susyboy23** [comment]
> use the create function you moron

create function?

**Comment by susyboy23** [comment]
you can explain it better please?

**Comment by DotWith** [comment]
> you can explain it better please?

Look at other states to see the create function

**Comment by DotWith** [comment]
Plus only sub-states use the new function

**Comment by susyboy23** [comment]
A ok

**Comment by susyboy23** [comment]
I check out if the other guys of the team whas using a old ver off this repository and actually they whas DX, now everything works fine
