### ISSUE TITLE
Videos will replay if user presses Enter, attempting to skip

### ISSUE THREAD

**Issue by deandimarzo** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#7]
If the user presses "Enter" (attempting to skip an MP4 cutscene), the video will start again _but with the original instance of the video still playing in the background._ This can lead to an endless pile of repeating videos stacked on top of each other.

Can we block input from the player during cutscenes, or add a "skip" feature?

**Comment by polybiusproxy** [comment]
Hi there!
Right now, videos don't check for input, so they can't be skippable.
When you press Enter, you're playing the video again, since it just adds the video.

However, I'm working on it.

**Comment by deandimarzo** [comment]
Fixed this one by adding a Bool flag in StoryMenuState.hx that gets turned on at the start of the cutscene, and if the cutscene gets triggered again, instead calls  `onVLCComplete()` to force the cutscene to end, and move on to the song.

**Comment by polybiusproxy** [comment]
> Fixed this one by adding a Bool flag in StoryMenuState.hx that gets turned on at the start of the cutscene, and if the cutscene gets triggered again, instead calls `onVLCComplete()` to force the cutscene to end, and move on to the song.

As I said in the other issue, mind making a pull request?
Thanks!
