### ISSUE TITLE
how did you set the path for linux?

### ISSUE THREAD

**Issue by McJonnycat** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#71]
how did you do it?

**Comment by polybiusproxy** [comment]
what do you mean?

**Comment by Jonnycatmeow** [comment]
i mean like how did you add it for linux cause im trying to fix the mp4 video for macos

**Comment by DotWith** [comment]
what?

**Comment by Jonnycatmeow** [comment]
ok do do you know how you added the linux libs right

**Comment by Jonnycatmeow** [comment]
so how did you make linux work for mp4 video support

**Comment by DotWith** [comment]
> so how did you make linux work for mp4 video support 

It's not ready yet

**Comment by MrClogsworthYT** [comment]
> i mean like how did you add it for linux cause im trying to fix the mp4 video for macos

i had a stroke reading this

**Comment by Jrgamer4u** [comment]
i think they were talking about https://github.com/brightfyregit/Friday-Night-Funkin-Mp4-Video-Support/tree/main/source/vlc/cpp/lib/linux

**Comment by TheDisabledKid** [comment]
> i think they were talking about https://github.com/brightfyregit/Friday-Night-Funkin-Mp4-Video-Support/tree/main/source/vlc/cpp/lib/linux

yeah cause i am trying to fix it for macos i can give them the libs for it as well
