### ISSUE TITLE
Add a option for hardware acceleration

### ISSUE THREAD

**Issue by DotWith** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#75]
When I looked into the code I found that hardware acceleration was enabled, and not everyone likes hwAcceleration as it can cause problems with programs that record your screen.

**Comment by TheRealJake12** [comment]
uhh like a option built into the engine used? im sure I could do it if someone gave me the code needed for my engine to toggle it.
or a seperate code entirely?

**Comment by DotWith** [comment]
> uhh like a option built into the engine used? im sure I could do it if someone gave me the code needed for my engine to toggle it. or a seperate code entirely?

It would be based on if the window used hardware.

**Comment by polybiusproxy** [comment]
> When I looked into the code I found that hardware acceleration was enabled, and not everyone likes hwAcceleration as it can cause problems with programs that record your screen.

Actually, HW Acceleration is disabled, because it doesn't works so well (libVLC causes a crash)

**Comment by DotWith** [comment]
bruh
