### ISSUE TITLE
Unknown identifier : playCutscene

### ISSUE THREAD

**Issue by SilentFunkin** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#77]
so I tried to build the game and this shows up
![dg](https://user-images.githubusercontent.com/86343451/147800915-e927dcdb-8716-4a70-a257-2dbff4ff7778.PNG)

im not the best coder so idk whats going on

**Comment by DotWith** [comment]
Sorry all the code was updated. Please try the new example at the bottom of the readme.

**Comment by SilentFunkin** [comment]
well now this happen
![bhu](https://user-images.githubusercontent.com/86343451/147859564-39ee8359-545f-420e-98b5-93d56855a589.PNG)
s

**Comment by DotWith** [comment]
> well now this happens ![bhu](https://user-images.githubusercontent.com/86343451/147859564-39ee8359-545f-420e-98b5-93d56855a589.PNG)

You have to add the code yourself and use the example.

**Comment by SilentFunkin** [comment]
uhhh what code exactly? pretend you are talking to someone who has no idea what their doing

**Comment by DotWith** [comment]
> uhhh what code exactly? pretend you are talking to someone who has no idea what their doing

`playEndCutscene` isn't required for all mods.
