### ISSUE TITLE
The volume setting won't work on videos

### ISSUE THREAD

**Issue by CryBitDev** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#8]
When i tune down or up the volume of the game, it doesn't affect the videos

**Comment by polybiusproxy** [comment]
That is being worked on.

**Comment by CryBitDev** [comment]
Okay!

**Comment by CryBitDev** [comment]
I am reopening this until it is fixed. This is probably for this to be a reminder of some sort

**Comment by polybiusproxy** [comment]
That is now fixed! The update will come soon.
