### ISSUE TITLE
Video Time updates slowly

### ISSUE THREAD

**Issue by ACrazyTown** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#84]
I'm making a subtitle system, and it relies on time to display text in sync with the video, however, I've noticed that the video time updates every few seconds, making it unsync the subtitles.

Is there any way to circumvent this or is it like an issue within the VlcBitmap stuff?

**Comment by polybiusproxy** [comment]
It may be an issue with libVLC itself, didn't test the video time that much.
