### ISSUE TITLE
Werid Pitch and Earrape Issues with the videos

### ISSUE THREAD

**Issue by djawesomeyt** [brightfyregit/Friday-Night-Funkin-Mp4-Video-Support#9]
Alright, sometime when playing a cutscene the cutscene that pitch can kinda go in and out a higher pitch at random sometimes. Then, when going out and replaying that same cutscene can cause it to get INCREDIBLY LOUD like earrape loud. Would be very unfortunate if people ears were destroyed while playing my mod.

**Comment by polybiusproxy** [comment]
huh?
on my tests, that didnt happened.

**Comment by polybiusproxy** [comment]
do u mean distortion?

**Comment by djawesomeyt** [comment]
maybe it has something to do with me using mic'd up

**Comment by polybiusproxy** [comment]
Please, provide the build where you are having that issue.

**Comment by djawesomeyt** [comment]
FNF Mic'd Up 2.0.2 main
